#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 mindreset
# SPDX-License-Identifier: Apache-2.0
# 从固定官方wheel生成离线表，不导入第三方代码。/ Generate from a pinned official wheel without importing third-party code.
import argparse
import hashlib
import json
from pathlib import Path
import unicodedata
import zipfile

VERSION = "0.55.0"
WHEEL_SHA256 = "d53b1e8ad2cdb815fb2cb604ed3123372f5a28c6f447571244aca36fc62a286f"
ROOT = Path(__file__).resolve().parents[1] / "components/read_pico_search"


def normalize(value):
    # ü保留为v，其余组合声调去除。/ Preserve ü as v and remove other combining tone marks.
    out = ""
    for c in unicodedata.normalize("NFD", value.lower()):
        if c == "\u0308" and out.endswith("u"):
            out = out[:-1] + "v"
        elif not unicodedata.combining(c):
            out += c
    if not out.isascii() or not out.isalpha():
        raise ValueError(f"Unsupported dictionary pronunciation: {value!r} -> {out!r}")
    return out


def array(name, ctype, values):
    lines = [f"static const {ctype} {name}[] = {{"]
    for i in range(0, len(values), 16):
        lines.append("    " + ", ".join(str(v) for v in values[i:i + 16]) + ",")
    return "\n".join(lines + ["};", ""])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("wheel", type=Path)
    args = parser.parse_args()
    digest = hashlib.sha256(args.wheel.read_bytes()).hexdigest()
    if digest != WHEEL_SHA256:
        raise ValueError("Wheel SHA-256 differs from the pinned official release")
    with zipfile.ZipFile(args.wheel) as wheel:
        metadata = wheel.read(f"pypinyin-{VERSION}.dist-info/METADATA").decode()
        assert f"Version: {VERSION}\n" in metadata
        entries = json.loads(wheel.read("pypinyin/pinyin_dict.json"))
        license_text = wheel.read(f"pypinyin-{VERSION}.dist-info/licenses/LICENSE.txt").decode()
    pronunciations = {int(cp): tuple(sorted(set(normalize(v) for v in values.split(","))))
                      for cp, values in entries.items()}
    syllables = sorted({v for values in pronunciations.values() for v in values})
    syllable_ids = {v: i for i, v in enumerate(syllables)}
    groups = sorted(set(pronunciations.values()))
    group_ids = {v: i for i, v in enumerate(groups)}
    chars = sorted(pronunciations)
    offsets, readings = [0], []
    for group in groups:
        readings.extend(syllable_ids[v] for v in group)
        offsets.append(len(readings))
    syllable_offsets, data = [], b""
    for syllable in syllables:
        syllable_offsets.append(len(data))
        data += syllable.encode() + b"\0"
    assert max(len(groups), len(readings), len(data)) < 65536
    output = """/*
 * SPDX-FileCopyrightText: 2026 mindreset
 * SPDX-License-Identifier: MIT
 * 由tools/generate_search_table.py生成；禁止手改。/ Generated by tools/generate_search_table.py; do not hand-edit.
 * 数据源与原作者许可见LICENSE.pypinyin和README.md。/ Data provenance and original license: LICENSE.pypinyin and README.md.
 */
"""
    output += array("search_codepoints", "uint32_t", chars)
    output += array("search_groups", "uint16_t", [group_ids[pronunciations[cp]] for cp in chars])
    output += array("search_group_offsets", "uint16_t", offsets)
    output += array("search_readings", "uint16_t", readings)
    output += array("search_syllable_offsets", "uint16_t", syllable_offsets)
    output += array("search_syllables", "char", list(data))
    ROOT.mkdir(parents=True, exist_ok=True)
    (ROOT / "search_table.h").write_text(output, encoding="utf-8", newline="\n")
    (ROOT / "LICENSE.pypinyin").write_text(license_text, encoding="utf-8", newline="\n")
    size = len(chars) * 6 + (len(offsets) + len(readings) + len(syllable_offsets)) * 2 + len(data)
    print(f"pypinyin {VERSION}; wheel sha256={digest}")
    print(f"{len(chars)} codepoints; {len(groups)} groups; {len(syllables)} syllables; const data {size} bytes")


if __name__ == "__main__":
    main()
